-- NTPA directors from CSV "Name,Email" — run in Supabase → SQL Editor
-- Duplicate email nmann@ntpa.org appears twice in source; delete one row in Table Editor if needed.

INSERT INTO public.directors (body)
SELECT jsonb_build_object(
  'full_name', trim(full_name),
  'email', lower(trim(email)),
  'phone', '',
  'organization', '',
  'notes', ''
)
FROM (VALUES
  ('Nick Mann', 'nmann@ntpa.org'),
  ('Sydni Casaubon', 'scasaubon@ntpa.org'),
  ('Angelica Zavala', 'azavala@ntpa.org'),
  ('Melissa Smith', 'msmith@ntpa.org'),
  ('Elizabeth Daffin', 'edaffin@ntpa.org'),
  ('Samantha Reser', 'sreser@ntpa.org'),
  ('Alix Gavin', 'agavin@ntpa.org'),
  ('Leslie Hill-King', 'lking@ntpa.org'),
  ('CIbby Bowden', 'cbowden@ntpa.org'),
  ('Morgan Vaughan', 'mvaughan@ntpa.org'),
  ('Jasmine Mathew', 'jmathew@ntpa.org'),
  ('Jessica Whiteman', 'jwhiteman@ntpa.org'),
  ('Bre Spink', 'bspink@ntpa.org'),
  ('Shanelle Leonard', 'sleonard@ntpa.org'),
  ('Hunter Brown', 'hbrown@ntpa.org'),
  ('Hannah Hoffman', 'hhoffman@ntpa.org'),
  ('Sophia Duncan', 'sduncan@ntpa.org'),
  ('Madison McNeely', 'mmcneely@ntpa.org'),
  ('Lynley Glickler', 'lglickler@ntpa.org'),
  ('Peyton Churchwell', 'pchurchwell@ntpa.org'),
  ('Tyler Overton', 'toverton@ntpa.org'),
  ('Kristie Schuh', 'kschuh@ntpa.org'),
  ('Anne Underwood', 'aunderwood@ntpa.org'),
  ('Riley Madlock', 'rmadlock@ntpa.org'),
  ('Charlotte Forcht', 'cforcht@ntpa.org'),
  ('Kerry Murdock', 'kmurdock@ntpa.org'),
  ('Paige Price', 'pprice@ntpa.org'),
  ('Riley Graygrove', 'rgraygrove@ntpa.org'),
  ('Katie Ames', 'kames@ntpa.org'),
  ('Hannah Brewer', 'hbrewer@ntpa.org'),
  ('See Pamela', 'spamela@ntpa.org'),
  ('Holly LaFevers', 'hlafevers@ntpa.org'),
  ('Jennifer Wheeler', 'jwheeler@ntpa.org'),
  ('Lyz Miller', 'lmiller@ntpa.org'),
  ('Major Attaway', 'mattaway@ntpa.org'),
  ('Linda McAdams', 'lmcadams@ntpa.org'),
  ('Zayde Vetter', 'zvetter@ntpa.org'),
  ('Shannon Hauser', 'shauser@ntpa.org'),
  ('Hannah Anderson', 'handerson@ntpa.org'),
  ('Kolby Campbell', 'kcampbell@ntpa.org'),
  ('Rachel Berros', 'rberros@ntpa.org'),
  ('Karen Snapp', 'ksnapp@ntpa.org'),
  ('MacKenzie Kern', 'mkern@ntpa.org'),
  ('Denice Forney', 'dforney@ntpa.org'),
  ('Kaylee Killingsworth', 'kkillingsworth@ntpa.org'),
  ('Austin Keefer', 'akeefer@ntpa.org'),
  ('Rachana Madhav', 'rmadhav@ntpa.org'),
  ('Daymond Sands', 'dsands@ntpa.org'),
  ('Nick Cutelli', 'ncutelli@ntpa.org'),
  ('Gregory McKnight', 'gmcknight@ntpa.org'),
  ('Emily Hamm', 'ehamm@ntpa.org'),
  ('Lizz Bashore', 'lbashore@ntpa.org'),
  ('Sunnie Saenz', 'ssaenz@ntpa.org'),
  ('Kameron Knott', 'kknott@ntpa.org'),
  ('Tammara Wright', 'twright@ntpa.org'),
  ('Noelle Saul', 'nsaul@ntpa.org'),
  ('Seigen Walker', 'swalker@ntpa.org'),
  ('Ken Simmons', 'ksimmons@ntpa.org'),
  ('Kaitlyn Barnard', 'kbarnard@ntpa.org'),
  ('Sid Polezcek', 'spolezcek@ntpa.org'),
  ('Nick Mann', 'nmann@ntpa.org'),
  ('Mike Mazur', 'mmazur@ntpa.org'),
  ('Niquel Barnett', 'nbarnett@ntpa.org'),
  ('Ivy Walker', 'iwalker@ntpa.org'),
  ('Malik Akil', 'makil@ntpa.org'),
  ('Lauren Webster', 'lwebster@ntpa.org'),
  ('Melissa Winton', 'mwinton@ntpa.org'),
  ('Brycen Bohl', 'bbohl@ntpa.org'),
  ('Brenna Peterson', 'bpeterson@ntpa.org'),
  ('Kelly Triece', 'ktriece@ntpa.org'),
  ('Alayna Meilinger', 'alayna@meilinger.com'),
  ('Olivia Elroz', 'oelroz@ntpa.org'),
  ('Lauren Robertson', 'lrobertson@ntpa.org'),
  ('Megan Hildebrand', 'mhildebrand@ntpa.org'),
  ('Allison Remley', 'aremley@ntpa.org'),
  ('Elena Maldonado-Dunn', 'edunn@ntpa.org')
) AS t(full_name, email)
WHERE trim(email) <> '';
